### PR TITLE
Fixed map_frame_to_utm_tf_publisher not waiting until lanelet2_interf…

### LINKED ISSUE #4: map_frame_to_utm_tf_publisher doesnt wait for parameters
In [map_frame_to_utm_tf_publisher.py](https://github.com/coincar-sim/lanelet2_interface_ros/blob/3f813442abcd792744ea40bf9dee2cdac87d68f7/scripts/map_frame_to_utm_tf_publisher.py#L60), the following loop is supposed to stall the node until all `/lanelet2_interface_ros/` rosparams are available:

```
    for i in range(3000):
        lat_origin = float(rospy.get_param("/lanelet2_interface_ros/lat_origin"))
        lon_origin = float(rospy.get_param("/lanelet2_interface_ros/lon_origin"))

        map_frame_id = rospy.get_param("/lanelet2_interface_ros/map_frame_id")
        actual_utm_with_no_offset_frame_id = rospy.get_param(
            "/lanelet2_interface_ros/actual_utm_with_no_offset_frame_id")
        if lat_origin is not None and lon_origin is not None \
                and map_frame_id is not None and actual_utm_with_no_offset_frame_id is not None:
            init = True
            break

        rospy.sleep(0.01)

    if not init:
        rospy.logerr("map_frame_to_utm_tf_publisher: Could not initialize")
        exit()
```

However, [get_param](http://wiki.ros.org/rospy/Overview/Parameter%20Server) actually raises a `KeyError` if the parameter is not present on the parameter server. Therefore, the whole loop is kinda meaningless, because if the parameters are present, the `is not None` checks will never fail and if they are not present, the script will exit due to the exception. By handling the exception e.g. in the following way
```
        try:
            map_frame_id = rospy.get_param("/lanelet2_interface_ros/map_frame_id")
        except Exception:
            pass
```
the checks will be useful again. However, you might need some special handling for the `float` casts there.

### PR DESCRIPTION
**Pull request by PPeltzer**
Fixed map_frame_to_utm_tf_publisher not waiting until lanelet2_interface_ros parameters are available (closes #4)

### CODE REVIEW

**Comment by m-naumann** [comment]
Looks good to me. @eduardo-molinos @einsteinguang can you please test this, and also look into why the pipeline is failing? On Apr 20, it was still working on travis, not many changes in the [mrt_cmake_modules](https://github.com/KIT-MRT/mrt_cmake_modules/commits/master) since then ;)

**Comment by einsteinguang** [comment]
@m-naumann following your recommendation, I should clone this merge-request manually and push them into gitlab to test the pipeline, then merge it there. How do I do that exactly? I don't understand how this merge request can be closed if the cloned one in gitlab closes.

**Comment by PPeltzer** [comment]
Any update on this? Merging this into upstream would be quite a help on my side :smile:

**Comment by einsteinguang** [comment]
We should merge this internally in our Gitlab and then this merge request will be merged automatically. However the same merge request in our Gitlab is blocked by the failed CI pipeline because of other package dependencies. We will merge this as soon as that issue is solved.

**Pull request merged**
